#
#
# Created by fergydanny, check out my other plugins at https://www.spigotmc.org/resources/authors/fergydanny.25236/
#
#

# Here you can specify domains that this plugin will ignore. Make sure to ad the subdomain too.
whitelisted-domains:
  - 'youtube.com'
  - 'server.com'
  - 'play.server.com'

# Specify the warning message players get when advertising.
warning-message: '&cPlease do not advertise again. Doing so will get you permanently banned!'

# Here you can specify after how many offenses a player is punished.
punishment-threshold: 3

# Here you specify what happens when they reach the above threshold, use %player% to substitute the player name.
punishment-command: '/ban %player% Advertising'

# Filter isn't catching a specific case? Add it here and if the message contains it, it will be caught.
custom-filters:
  - 'mc()potato()com'

# Do you want the entire chat to be cleared when a users message is flagged for advertising?
clear-chat: true

# Here you can customize the chat cleared message
clear-chat-message:
  - '&7&m---------------------------------'
  - ' '
  - '        &eThe chat has been cleared!'
  - '          &7(Reason: Advertisement)'
  - ' '
  - '&7&m---------------------------------'

# Here you set which filters are enabled or disabled
url-filter: true # This filter blocks any urls that are not in the above whitelisted-domains. Works for potato.com, mc.potato.com, potato.com/potato
bypass-filter: true # This filter prevents obvious bypasses. Currently blocks users saying stuff like mc dot potato dot com.
numberedip-filter: true # This one simply blocks all numbered ips. For example: 127.0.0.1
custom-filter: true # This one checks messages to see if they contain the exact strings in the above custom-filters section.

# Whether or not to toggle debug messages in console (helps you see how the filter catches a message)
debug: false

#
#
# The End
#
#